import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/di/database_provider.dart';
import '../../data/drift/database.dart';

// Written as plain (non-generated) providers: riverpod_generator's analyzer
// step can throw InvalidTypeException when a provider's return type is a
// class generated by a *different* generator (here: drift's row classes)
// in the same build_runner pass (see rrousselGit/riverpod#4323). Plain
// providers sidestep codegen entirely, so there is no cross-generator
// ordering issue.

final runningEntryProvider = StreamProvider<TimeEntry?>((ref) {
  return ref.watch(appDatabaseProvider).timeEntriesDao.watchRunningEntry();
});

final allEntriesProvider = StreamProvider<List<TimeEntry>>((ref) {
  return ref.watch(appDatabaseProvider).timeEntriesDao.watchAllEntries();
});

/// Ticks once a second purely to force widgets displaying the running
/// entry's elapsed time to rebuild; the duration itself is always computed
/// fresh from [runningEntryProvider]'s startAt vs DateTime.now().
final timerTickProvider = StreamProvider<int>((ref) {
  return Stream<int>.periodic(const Duration(seconds: 1), (i) => i);
});
